# Generated by Django 6.0.1 on 2026-01-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nickname', models.CharField(max_length=50)),
                ('jlpt_level', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
                ('major', models.CharField(max_length=50)),
                ('goal', models.CharField()),
                ('age', models.PositiveIntegerField()),
                ('interests', models.JSONField(default=list)),
                ('work_fields', models.JSONField(default=list)),
                ('skills', models.JSONField(default=list)),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
